django/art979/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin

from art979.feeds import EventsFeed, StoriesFeed, VenueUpdatesFeed

admin.autodiscover()

feeds = {
    'events': EventsFeed,
    'stories': StoriesFeed,
    'venueupdates': VenueUpdatesFeed,
}

urlpatterns = patterns('',
## Static Media Serving ##
	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/media/Storage/programming/web/art979.com/httpdocs/media'}),

## Extras ##
    (r'^feeds/(?P<url>.*)/$', 'django.contrib.syndication.views.feed', {'feed_dict': feeds}),
)

urlpatterns += patterns('art979.Page.views',

## Administration Urls ##
    (r'^thanks/$', 'thanks'),
    (r'^activate/$', 'activate'),
    (r'^verifyemail/$', 'verify_email'),

## Category Urls ##
    (r'^music/genres/(?P<genre_id>.*)/$', 'music_genre'),
    (r'^film/genres/(?P<genre_id>.*)/$', 'film_genre'),
    (r'^literary/genres/(?P<genre_id>.*)/$', 'literature_genre'),
    (r'^(?P<category>visual|music|culinary|literary|artisan|design|performing)/$', 'category'),
    (r'^(?P<category>visual|music|culinary|literary|artisan|design|performing)/(?P<artist_category>.*)/$', 'artist_category'),

## Flat Urls ##
    (r'^gallery/$', 'gallery'),
    (r'^events/$', 'events'),
    (r'^register/$', 'register'),
    (r'^test/$', 'test'),

## Story Urls ##
    (r'^stories/(?P<story_id>\d*)/$', 'story'),

## Event Urls ##
    (r'^events/(?P<event_id>\d*)/$', 'event_profile'),
    (r'^events/(?P<event_type>.*)/$', 'events'),

## Venue Urls ##
    (r'^venues/(?P<venue_id>\d*)/$', 'venue_profile'),
    (r'^venues/(?P<venue_type>.*)/$', 'venues'),

## Artist Urls ##
    (r'^artists/(?P<artist_id>\d*)/(?P<art_type>all|songs|albums|visualpieces|food|films|literaturepieces|performingpieces)/$', 'artist_art'),
    (r'^artists/(?P<artist_id>\d*)/(?P<art_type>songs|albums|visualpieces|food|films|literaturepieces|performingpieces)/(?P<art_id>\d*)/$', 'art_profile'),
    (r'^artists/(?P<artist_id>\d*)/$', 'artist_profile'),

## Group Urls ##
    (r'^bands/(?P<band_id>\d*)/$', 'band_profile'),
    (r'^bands/$', 'bands'),
    (r'^organizations/(?P<organization_id>\d*)/$', 'organization_profile'),
    (r'^organizations/$', 'organizations'),

## Account Urls ##
    (r'^account/create/(?P<model_type>art|event|venue|story|band|organization)/(\b|(?P<art_type>song|album|visualpiece|food|film|literaturepiece|performingpiece)/)$', 'model_create'),
    (r'^account/edit/(?P<model_type>art|event|venue|story|band|organization)/((?P<art_type>song|album|visualpiece|food|film|literaturepiece|performingpiece)/(?P<art_id>\d*)|(?P<model_id>\d*))/$', 'model_edit'),
    (r'^account/delete/(?P<model_type>art|event|venue|story|band|organization)/((?P<art_type>song|album|visualpiece|food|film|literaturepiece|performingpiece)/(?P<art_id>\d*)|(?P<model_id>\d*))/$', 'model_delete'),
    (r'^account/get/(?P<model_type>all|art|event|venue|story|band|organization)/(\b|(?P<art_type>song|album|visualpiece|food|film|literaturepiece|performingpiece)/(?P<art_id>\d*)|(?P<model_id>\d*))/$', 'model_get'),
    (r'^account/options/$', 'account_options'),
    (r'^account/$', 'account'),
    (r'^deleteaccount/$', 'account_delete'),

## Home/Admin ##
    (r'^$', 'home'),
    (r'^admin/(.*)', admin.site.root),
)

django/art979/Category/models.py
from django.db import models

class CategoryBase(models.Model):
    name = models.CharField(max_length=100)
    plural = models.CharField(max_length=100, blank=True, help_text='Should be capitalized.')
    description = models.TextField(blank=True)
    pub_date = models.DateTimeField('date created', auto_now_add=True, editable=False)
    last_modified = models.DateTimeField('date last modified', auto_now=True, editable=False)

    class Meta:
        abstract = True

    def _get_stub_from_name(self):
        return self.name.tolower().replace(" ", "")
    stub = property(_get_stub_from_name)

class ArtistCategory(CategoryBase):
    SUBJECT_CHOICES = (
        ('visual', 'Visual Arts'),
        ('music', 'Music'),
        ('culinary', 'Culinary Arts'),
        ('literary', 'Literary Arts'),
        ('artisan', 'Artisan'),
        ('design', 'Design'),
        ('performing', 'Performing Arts'),
    )

    subject = models.CharField(max_length=10, choices=SUBJECT_CHOICES)
    art_noun = models.CharField(max_length=100, help_text='Noun to display for art pieces in this category.')

    class Meta:
        verbose_name = 'Artist Category'
        verbose_name_plural = 'Artist Categories'

    def get_absolute_url(self):
        return "/%s/%s/" % (self.subject, self.stub)

    def __unicode__(self):
        return self.name

class MusicGenre(CategoryBase):
    ## attributes
    subject = 'music'

    class Meta:
        verbose_name = 'Music Genre'
        verbose_name_plural = 'Music Genres'

    def get_absolute_url(self):
        return "/music/genres/%s/" % self.id

    def __unicode__(self):
        return "Music | %s" % self.name

class FilmGenre(CategoryBase):
    ## attributes
    subject = 'visual'
    
    class Meta:
        verbose_name = 'Film Genre'
        verbose_name_plural = 'Film Genres'

    def get_absolute_url(self):
        return "/film/genres/%s/" % self.id

    def __unicode__(self):
        return "Film | %s" % self.name

class LiteratureGenre(CategoryBase):
    ## attributes
    subject = 'literary'

    class Meta:
        verbose_name = 'Literature Genre'
        verbose_name_plural = 'Literature Genres'

    def get_absolute_url(self):
        return "/literary/genres/%s/" % self.id

    def __unicode__(self):
        return "Literature | %s" % self.name

class VenueType(CategoryBase):
    class Meta:
        verbose_name = 'Venue Type'
        verbose_name_plural = 'Venue Types'

    def get_absolute_url(self):
        return "/venues/%s/" % self.stub

    def __unicode__(self):
        return "Venue | %s" % self.name

class EventType(CategoryBase):
    class Meta:
        verbose_name = 'Event Type'
        verbose_name_plural = 'Event Types'

    def get_absolute_url(self):
        return "/events/%s/" % self.stub

    def __unicode__(self):
        return "Event | %s" % self.name

django/art979/Event/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from art979.Category.models import EventType
from art979.Profile.models import Band
from art979.Art.models import Album, Song, LiteraturePiece, VisualPiece, Film, Food, PerformingPiece
from art979.Venue.models import Venue
from art979.utils import image_path
from art979.Event.custom import RecurringDateField

class Event(models.Model):
    """
    An event that can reference a venue it takes place at, multiple artsists/bands/organizations,
    multiple art pieces, and users that are following it.

    # Create some events
    >>> concert = Event.objects.create(name="concert", url="http://art979.com/")

    """
    ## attributes
    name = models.CharField(_('name'), max_length=300)
    url = models.URLField(_('url'), blank=True)
    image = models.ImageField(_('image'), upload_to=image_path, blank=True)
    date = RecurringDateField(_('Date'), blank=True)
    pub_date = models.DateTimeField(_('publication date'), 'date created', auto_now_add=True)
    last_modified = models.DateTimeField(_('last modified'), 'date last modified', auto_now=True)
    ticket_prices = models.CharField(_('ticket prices'), max_length=75, blank=True)
    bio = models.TextField(_('bio'), blank=True)

    ## options ##
    published = models.BooleanField(_('published option'), default=False, editable=True)

    ## relations
    user = models.ForeignKey(User, editable=False)
    type = models.ForeignKey(EventType, related_name='events')
    venue = models.ForeignKey(Venue, blank=True, null=True, related_name='events')
    artists = models.ManyToManyField(User, blank=True, null=True, related_name='events')
    bands = models.ManyToManyField(Band, blank=True, null=True, related_name='events')
    albums = models.ManyToManyField(Album, blank=True, null=True, related_name='events')
    songs = models.ManyToManyField(Song, blank=True, null=True, related_name='events')
    performing_pieces = models.ManyToManyField(PerformingPiece, blank=True, null=True, related_name='events')
    visual_pieces = models.ManyToManyField(VisualPiece, blank=True, null=True, related_name='events')
    literature_pieces = models.ManyToManyField(LiteraturePiece, blank=True, null=True, related_name='events')
    films = models.ManyToManyField(Film, blank=True, null=True, related_name='events')
    food = models.ManyToManyField(Food, blank=True, null=True, related_name='events')
    followers = models.ManyToManyField(User, blank=True, null=True, related_name='followed_events')

    def _get_stub_from_name(self):
        return self.name.tolower().replace(" ", "")
    stub = property(_get_stub_from_name)

    def get_absolute_url(self):
        return "/events/%s/" % (self.id)

    def __unicode__(self):
        return self.name

django/art979/Profile/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.localflavor.us.models import PhoneNumberField
from django.utils.translation import ugettext_lazy as _

from art979.Category.models import ArtistCategory, MusicGenre
from art979.Venue.models import Venue

class UserProfile(models.Model):
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )

    ## attributes
    url = models.URLField(_('web address'), blank=True, null=True)
    phone_number = PhoneNumberField(_('phone number'), blank=True, null=True)
    bio = models.TextField(_('bio'), blank=True, null=True)
    location = models.CharField(_('location'), max_length=150, blank=True, null=True)
    birth_date = models.DateField(_('birth Date'), blank=True, null=True)
    occupation = models.CharField(_('occupation'), max_length=150, blank=True, null=True)
    interests = models.TextField(_('interests'), blank=True, null=True)
    zip = models.CharField(_('zip code'), max_length=10, blank=True, null=True)
    gender = models.CharField(_('gender'), max_length=1, choices=GENDER_CHOICES, blank=True, null=True)
    pub_date = models.DateTimeField(_('date created'), auto_now_add=True)
    last_modified = models.DateTimeField(_('last modified'), auto_now=True)
    
    ## user_options
    confirmed = models.BooleanField(_('confirmed'), default=False, editable=False)
    artist_profile = models.BooleanField(_('artist profile option'), default=False)
    show_email = models.BooleanField(_('show email option'), default=False)
    has_avatar = models.BooleanField(_('has avatar option'), default=False)
    gets_updates = models.BooleanField(_('get updates option'), default=False)

    ## relations
    user = models.ForeignKey(User, unique=True, editable=False) ## AUTH_PROFILE_MODULE
    categories = models.ManyToManyField(ArtistCategory, blank=True, related_name="users")
    favorite_venues = models.ManyToManyField(Venue, blank=True, related_name="users")

    def _get_username(self):
        return self.user.username
    username = property(_get_username)

    def _get_email(self):
        return self.user.email
    email = property(_get_email)

    def __unicode__(self):
        return self.user.username

    def get_absolute_url(self):
        if artist_profile:
            return "/artists/%s/" % self.user.id
        return "/"

class Organization(models.Model):
    ## attributes
    name = models.CharField(_('name'), max_length=300)
    bio = models.TextField(_('bio'), )
    pub_date = models.DateTimeField(_('date created'), auto_now_add=True)
    last_modified = models.DateTimeField(_('last modified'), auto_now=True)

    ## relations
    admin = models.ForeignKey(User, editable=False)
    members = models.ManyToManyField(User, blank=True, related_name="organizations", through="OrganizationMembership")

    def _get_stub_from_name(self):
        return self.name.tolower().replace(" ", "")
    stub = property(_get_stub_from_name)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/organizations/%s/" % self.id

class Band(models.Model):
    ## attributes
    name = models.CharField(_('name'), max_length=300)
    bio = models.TextField(_('bio'), )
    pub_date = models.DateTimeField(_('date created'), auto_now_add=True)
    last_modified = models.DateTimeField(_('last modified'), auto_now=True)

    ## relations
    admin = models.ForeignKey(User, editable=False)
    members = models.ManyToManyField(User, blank=True, related_name="bands", through="BandMembership")
    genres = models.ManyToManyField(MusicGenre, related_name="bands")

    def _get_stub_from_name(self):
        return self.name.tolower().replace(" ", "")
    stub = property(_get_stub_from_name)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/bands/%s/" % self.id

class OrganizationMembership(models.Model):
    ## attributes
    date_joined = models.DateField(_('date Joined'), blank=True)
    position = models.CharField(_('position'), max_length=300, blank=True)

    ## relations
    organization = models.ForeignKey(Organization)
    user = models.ForeignKey(User)

class BandMembership(models.Model):
    ## attributes
    date_joined = models.DateField(_('date Joined'), blank=True)
    position = models.CharField(_('position'), max_length=300, blank=True)

    ## relations
    band = models.ForeignKey(Band)
    user = models.ForeignKey(User)

django/art979/Venue/models.py
from django.db import models
from django.contrib.auth.models import User
from art979.Category.models import VenueType
from art979.utils import image_path

class Venue(models.Model):
    ## attributes
    name = models.CharField(max_length=300)
    location = models.CharField(max_length=300)
    image = models.ImageField(upload_to=image_path, blank=True)
    email = models.EmailField(max_length=100)
    pub_date = models.DateTimeField('date created', auto_now_add=True, editable=False)
    last_modified = models.DateTimeField('date last modified', auto_now=True, editable=False)
    url = models.URLField(blank=True)
    bio = models.TextField()

    ## relations
    user = models.ForeignKey(User)
    type = models.ManyToManyField(VenueType, related_name='venues')

    class Meta:
        verbose_name = "Venue"
        verbose_name_plural = "Venues"

    def __unicode__(self):
        return self.name

    def _get_stub_from_name(self):
        return self.name.tolower().replace(" ", "")
    stub = property(_get_stub_from_name)

    def get_absolute_url(self):
        return "/venues/%s/" % (self.id)

django/art979/Event/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _

from art979.Event.models import Event

class CreateEventForm(forms.ModelForm):
    class Meta:
        model = Event

class EditEventForm(forms.ModelForm):
    class Meta:
        model = Event

django/art979/Profile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from art979.Profile.models import UserProfile, Band, Organization

class CreateBandForm(forms.ModelForm):
    class Meta:
        model = Band

class EditBandForm(forms.ModelForm):
    class Meta:
        model = Band

class CreateOrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization

class EditOrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization

class RegisterForm(forms.ModelForm):
    username = forms.RegexField(
            label = _('Username'),
            max_length = 45,
            regex = r'^\w+$',
            help_text = _('Required. 30 characters or fewer. Alphanumeric characters only (letters, digits, and underscores).'), 
            error_message = _('This field must contain only letters, numbers and underscores.')
            )
    password1 = forms.CharField(
            label = _('Password'),
            widget = forms.PasswordInput
            )
    password2 = forms.CharField(
            label = _('Password Confirmation'),
            widget = forms.PasswordInput
            )
    first_name = forms.CharField(
            label = _('First Name')
            )
    last_name = forms.CharField(
            label = _('Last Name')
            )

    email = forms.EmailField(
            label = _('Email Address')
            )

    class Meta:
        model = UserProfile
        fields = ['username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'artist_profile', 'gender', 'birth_date', 'location', 'occupation', 'phone_number', 'bio', 'interests', 'categories', 'show_email', 'has_avatar', 'gets_updates']

    def clean_username(self):
        username = self.cleaned_data["username"]
        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username
        raise forms.ValidationError(_("A user with that username already exists."))

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1", "")
        password2 = self.cleaned_data["password2"]
        if password1 != password2:
            raise forms.ValidationError(_("The two password fields didn't match."))
        return password2

django/art979/Category/views.py
# Create your views here.

django/art979/Event/views.py
# Create your views here.

django/art979/Profile/views.py
# Create your views here.

django/art979/templates/account.html
{% extends "base.html" %}

{% block body %}

<div class="span-24">
<div class="grey span-24">
<div id="profile_container">

<div id="profile_nav">

  <ul>

    {% if perms.Profiles.add_artist %}
    {% ifequal menu_option "profile" %}
      <li><a href="/account/profile/" class="current_option"><span>Profile</span></a></li>
    {% else %}
      <li><a href="/account/profile/"><span>Profile</span></a></li>
    {% endifequal %}

    {% ifequal menu_option "art" %}
      <li><a href="/account/art/" class="current_option"><span>Art Pieces</span></a></li>
    {% else %}
      <li><a href="/account/art/"><span>Art Pieces</span></a></li>
    {% endifequal %}
    {% endif %}

    {% if perms.Profiles.add_event %}
    {% ifequal menu_option "event" %}
      <li><a href="/account/event/" class="current_option"><span>Upcoming Events</span></a></li>
    {% else %}
      <li><a href="/account/event/"><span>Upcoming Events</span></a></li>
    {% endifequal %}

    {% ifequal menu_option "event-old" %}
      <li><a href="/account/event-old/" class="current_option"><span>Old Events</span></a></li>
    {% else %}
      <li><a href="/account/event-old/"><span>Old Events</span></a></li>
    {% endifequal %}
    {% endif %}

    {% if perms.Profiles.add_venue %}
    {% ifequal menu_option "venue" %}
      <li><a href="/account/venue/" class="current_option"><span>Venues</span></a></li>
    {% else %}
      <li><a href="/account/venue/"><span>Venues</span></a></li>
    {% endifequal %}
    {% endif %}

    {% if user.is_staff %}
    {% ifequal menu_option "story" %}
      <li><a href="/account/story/" class="current_option"><span>Stories</span></a></li>
    {% else %}
      <li><a href="/account/story/"><span>Stories</span></a></li>
    {% endifequal %}
    {% endif %}

    {% ifequal menu_option "options" %}
      <li><a href="/account/options/" class="current_option"><span>Account Options</span></a></li>
    {% else %}
      <li><a href="/account/options/"><span>Account Options</span></a></li>
    {% endifequal %}


  </ul>

</div>

<div class="span-24 profile_content">
    {% ifequal menu_option "profile" %}
      {% include "account/profile.html" %}
    {% endifequal %}

    {% ifequal menu_option "art" %}
      {% include "account/art.html" %}
    {% endifequal %}

    {% ifequal menu_option "venue" %}
      {% include "account/venues.html" %}
    {% endifequal %}

    {% ifequal menu_option "event" %}
      {% include "account/events.html" %}
    {% endifequal %}

    {% ifequal menu_option "event-old" %}
      {% include "account/events_old.html" %}
    {% endifequal %}

    {% if user.is_staff %}
    {% ifequal menu_option "story" %}
      {% include "account/stories.html" %}
    {% endifequal %}
    {% endif %}

    {% ifequal menu_option "options" %}
      {% include "account/options.html" %}
    {% endifequal %}
</div>

</div>
</div>
</div>

{% endblock %}

django/art979/templates/artists.html
{% extends "base.html" %}

{% block title %}
{%if category%}{{ category.name }} |{%endif%} Artists
{% endblock %}

{% block body %}

<div class="span-24">
  <div class="category_header">
    <h2>Artists - {{ category.name }}</h2>
    <p>{{ category.description }}</p>
    <div class="page_links_boxHeader">
      <div></div>
    </div>
    <div class="page_links_box">
    <p class="page_links"><a href="" class="page_button prev_button" rel="prev">prev</a><a href="" class="page_button next_button" rel="next">next</a>{%for page in paginator.page_range%}<a href="" class="page_button" rel="{{page}}">{{page}}</a> {%endfor%}</p>
    </div>
    <div class="page_links_boxFooter">
      <div></div>
    </div>
  </div>
</div>

<div class="span-24">
  <div class="span-18 artists">
    <div class="page_wrapper">
    {% for story in stories %}
      <div class="page-{{page.number}}">
      {% for artist in artists %}
        <div class="span-9 smallProfile{%cycle '' ' last'%}">
          <div class="smallProfileHeader">
            <h4><a href="/artist/{{artist.key}}/artist/">{{artist.first_name}} {{artist.last_name}}</a></h4>
          </div>
          <div class="smallProfileBody">
            <a class="smallProfileImage" href="/artist/{{artist.key}}/artist/"><img src="/media/{{artist.profile_image}}" alt="{{artist.first_name}} {{artist.last_name}}"/></a>
            <p>{{artist.bio|truncatewords:70}} <a href="/artist/{{artist.key}}/artist/">read more<img class="read_more" src="/media/img/read_more.gif" alt="Read More"/></a></p>
          </div>
        </div>
      {% endfor %}
      </div>
    {% endfor %}
    </div>

  </div>

  <div class="span-6 last sidebar">
    {% include "sidebar/events.html" %}
    <hr />
    {% include "sidebar/venues.html" %}
  </div>

</div>

{% endblock %}

django/art979/templates/category.html
{% extends "base.html" %}

{% block title %}
  {{ category.name }}
{% endblock %}

{% block body %}
<div class="span-24 category_header">
  <h2>{{ category.name }} - News</h2>
  <p>{{ category.description }}</p>
</div>
<div class="span-24 feature">
  <a href="#"><img src="{{feature.image_lg}}"/></a>
  <a href="#"><p>{{feature.body|truncatewords:120}}</p></a>
</div>
<div class="span-24 subfeatures">
  <div class="span-18 colborder">
    {% for story in stories %}
    <div class="span-6{%cycle '' '' ' last'%}">
      <a href="#"><img src="{{story.image_sm}}"></a>
      <a href="#"><p>{{story.body|truncatewords:20}}</p></a>
    </div>
    {% endfor %}
  </div>
  <div class="span-5 last">
    {% include "sidebar/events.html" %}
    <hr />
    {% include "sidebar/artists.html" %}
    <hr />
    {% include "sidebar/venues.html" %}
  </div>
</div>
{% endblock %}

django/art979/templates/confirm.html
{% extends "base.html" %}

{% block title %}Account Confirmation{% endblock %}
{% block body %}

<div class="span-24">
  
  <div class="span-18 append-1 confirm">
  {% if type %}
    {% ifequal acc "artlover" %}
    <p>Hello {{type.first_name}}, thank you for registering for regular updates from art979.com. If you ever wish to cancel your subscription just click the cancel link in your next email from us.</p>
    {% endifequal %}
    {% ifequal acc "artcoordinator" %}
    <p>Hello {{applicant.username}}, thank you for registering as an Art Coordinator at Art979. We are now in the process of reviewing your information and we will contact you as soon as your account is made active.</p>
    {% endifequal %}
    {% ifequal acc "artist" %}
    <p>Hello {{applicant.username}}, thank you for registering as an Artist at Art979. We are now in the process of reviewing your information and we will contact you as soon as your account is made active.</p>
    {% endifequal %}
  {% else %}
    <p>The account has been enabled</p>
  {% endif %}
  </div>

  <div class="span-5 last sidebar">
    <br />
    {% include "sidebar/events.html" %}
    <hr />
    {% include "sidebar/artists.html" %}
    <hr />
    {% include "sidebar/venues.html" %}
  </div>

</div>
{% endblock %}

django/art979/templates/dontdothat.html
{% extends "base.html" %}

{% block body %}
<div class="span-24">
  
  <div class="span-18 append-1">

    <p>Please don't change the cookie data for this site. It makes a mess.</p>

  </div>

  <div class="span-5 last sidebar">
    <br />
    {% include "sidebar/events.html" %}
    <hr />
    {% include "sidebar/artists.html" %}
    <hr />
    {% include "sidebar/venues.html" %}
  </div>

</div>
{% endblock %}

django/art979/templates/events.html
{% extends "base.html" %}

{% block title %}
{%if category%}{{ category.name }} |{%endif%} Events
{% endblock %}

{% block body %}

<div class="span-24">
  <div class="category_header">
    <h2>{%if category%}{{ category.name }} - Events{%else%}Events{%endif%}</h2>
    <p>{{ category.description }}</p>
    <div class="page_links_boxHeader">
      <div></div>
    </div>
    <div class="page_links_box">
    <p class="page_links"><a href="" class="page_button prev_button" rel="prev">prev</a><a href="" class="page_button next_button" rel="next">next</a>{%for page in paginator.page_range%}<a href="" class="page_button" rel="{{page}}">{{page}}</a> {%endfor%}</p>
    </div>
    <div class="page_links_boxFooter">
      <div></div>
    </div>
  </div>
</div>

<div class="span-24">
  <div class="span-18 events">

    <div class="page_wrapper">
    {% for page in pages %}
      <div class="page-{{page.number}}">
      {% if page.object_list %}
      {% for event in page.object_list %}
        <div class="span-9 smallProfile{%cycle '' ' last'%}">
          <div class="smallProfileHeader">
            <h4><a href="/event/{{event.key}}/">{{event.name}}</a></h4>
          </div>
          <div class="smallProfileBody">
            <a class="smallProfileImage" href="/event/{{event.key}}/"><img src="/media/{{event.image}}" alt="{{event.name}}"/></a>
            <p>{{event.description|truncatewords:70}} <a href="/event/{{event.key}}/">read more<img class="read_more" src="/media/img/read_more.gif" alt="Read More"/></a></p>
          </div>
        <div class="smallProfileFooter">
          <div></div>
        </div>
        </div>
      {% endfor %}
      {% else %}
      <h2>There are no events on this day</h2>
      {% endif %}
      </div>
    {% endfor %}
    </div>

  </div>

  <div class="span-6 last sidebar">
    {% include "sidebar/artists.html" %}
    <hr />
    {% include "sidebar/venues.html" %}
  </div>

</div>

{% endblock %}

django/art979/templates/home.html
{% extends "base.html" %}

{% block body %}
<div class="span-24 feature">
  <a href="#"><img src="{{feature.image_lg}}"/></a>
  <a href="#"><p>{{feature.body|truncatewords:120}}</p></a>
</div>
<div class="span-24 subfeatures">
  <div class="span-18 colborder">
    {% for story in stories %}
    <div class="span-6{%cycle '' '' ' last'%}">
      <a href="#"><img src="{{story.image_sm}}"></a>
      <a href="#"><p>{{story.body|truncatewords:20}}</p></a>
    </div>
    {% endfor %}
  </div>
  <div class="span-5 last">
    <h3>Events</h3>
    <dl>
      <dt>Concert #1</dt>
      <dd class="small">August 4th, 7PM</dd>
      <dt>Concert #1</dt>
      <dd class="small">August 4th, 7PM</dd>
      <dt>Concert #1</dt>
      <dd class="small">August 4th, 7PM</dd>
      <dt>Concert #1</dt>
      <dd class="small">August 4th, 7PM</dd>
    </dl>
  </div>
</div>
{% endblock %}